export const SET_TASKS = 'SET_TASKS';
export const RESET_TASKS = 'RESET_TASKS';
export const CHANGE_NAVBAR = 'CHANGE_NAVBAR';

export const SET_TASK_QUANTITY_INFO = 'SET_TASK_QUANTITY_INFO';
export const SET_ACTIVE_TASK = 'SET_ACTIVE_TASK';
export const ADD_TASK_COMMENT = 'ADD_TASK_COMMENT';
export const SET_ACTIVE_TASK_COMMENTS = 'SET_ACTIVE_TASK_COMMENTS';
export const CLEAR_ACTIVE_TASK_COMMENTS = 'CLEAR_ACTIVE_TASK_COMMENTS';
